version: '3.8'

networks:
  infrast-net:

services:
  infrast-general:
    image: postgres:15.3
    container_name: infrast-general
    networks:
      - infrast-net
    environment:
      POSTGRES_USER: infrast
      POSTGRES_PASSWORD: infrastpass
      POSTGRES_DB: infrastdb
    volumes:
      - ../../database/generalpg:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U infrast -d infrastdb']
      interval: 10s
      timeout: 5s
      retries: 5

  infrast-user-management:
    image: postgres:15.3
    container_name: infrast-user-management
    networks:
      - infrast-net
    environment:
      POSTGRES_USER: infrastum
      POSTGRES_PASSWORD: infrastumpass
      POSTGRES_DB: infrastdbum
    volumes:
      - ../../database/umpg:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U infrastum -d infrastdbum']
      interval: 10s
      timeout: 5s
      retries: 5
  
  mongodb:
    image: mongo:jammy
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: infrast
      MONGO_INITDB_ROOT_PASSWORD: infrastpass
    volumes:
      - ../../database/mongodb_data:/data/db