version: '3.8'

networks:
  infrast-net:

services:
  postgresql:
    image: postgres:latest
    container_name: infrast-postgresql
    networks:
      - infrast-net
    environment:
      POSTGRES_USER: infrast
      POSTGRES_PASSWORD: infrastpass
      POSTGRES_DB: infrastdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U infrast -d infrastdb']
      interval: 10s
      timeout: 5s
      retries: 5
